logging:
  level:
    org:
      springframework:
        security: DEBUG
server:
  port: 8000

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090/realms/oauth-demo-realm